name: Run Jupyter Notebook

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert atproto pandas pyarrow keyring

      - name: Run Jupyter Notebook
        env:
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          ELMTEST: ${{ secrets.ELMTEST }}
        run: |
          jupyter nbconvert --to script track_followers_count.ipynb
          python track_followers_count.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Update followers data [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
